### ISSUE TITLE
TemplateInspector outputs empty string instead in the deploy yml instead of 'no value'

### ISSUE THREAD

**Issue by jranson** [aperepel/nifi-api-deploy#21] opened 2016-05-12 19:32 UTC
When we have attributes that need to be represented as 'no value', in the deployment yaml for example:
          Access Key: 
          Secret Key: 
          Credentials File: 

Those are being inserted by the TemplateInspector as:
          Access Key: ''
          Secret Key: ''
          Credentials File: ''

This is causing the NiFiDeploy.groovy to fail to deploy the flow until we hand-edit the yml file to correct the issue.

**Comment by aperepel** [comment] 2016-05-12 19:39
Hey @jranson , these are generally special properties, marked as 'sensitive' in the UI. Are you observing the issue with other 'normal' property values?

Basically, for sensitive property values, the template will **never** export the actual value, it is write-only, by design. The deployment spec file is treated as an overlay over a template to override properties. It is recommended to remove everything except for the values you want customized.

With above comments, does it address your issue? Let me know if not and we can dig in.

**Comment by jranson** [comment] 2016-05-12 19:51
Hi Andrew, I'll check with my colleagues on what values they are seeing this in, and if they are marked as sensitive and get back to you. Thanks for the quick followup!

**Comment by davetorok** [comment] 2016-05-12 19:54
Hi, this is happening on any attribute with an unset / empty value... for example in LogAttribute the properties "Attributes to Log", "Attributes to Ignore", "Log Prefix".

**Comment by aperepel** [comment] 2016-05-12 22:06
Thank you guys. I finally managed to reproduce, fix committed. Let me know if that resolves your issue.

**Closed as completed** 2016-05-12 22:06 UTC
Labels: bug
