### ISSUE TITLE
Resolve Controller Service references by name instead of UUID

### ISSUE THREAD

**Issue by hijakk** [aperepel/nifi-api-deploy#14] opened 2016-04-21 21:15 UTC
Howdy, as an extension of issue #12 - this is the problem I'm seeing with the controllerServices. I don't know if it's unique to this particular controller, or more, but the attached is an example flow with a DBCP controller that starts and works fine with a local postgres database I have, but refuses to undeploy. If halted and deleted manually, the deployment with NiFiDeploy.groovy works fine. The error encountered follows:

```
$ groovy NiFiDeploy.groovy -f dbtest.yml
Loading Process Groups from NiFi
Undeploying Controller Service: T1
[ERROR] HTTP call failed. Status code: HTTP/1.1 409 Conflict: This NiFi instance has been updated by 'anonymous'. Please refresh to synchronize the view.
Caught: java.lang.AssertionError: Terminated script execution. Expression: null
java.lang.AssertionError: Terminated script execution. Expression: null
    at NiFiDeploy$_run_closure2.doCall(NiFiDeploy.groovy:526)
    at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1142)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1076)
    at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
    at groovyx.net.http.RESTClient.put(RESTClient.java:163)
    at groovyx.net.http.RESTClient$put$0.call(Unknown Source)
    at NiFiDeploy._changeControllerServiceState(NiFiDeploy.groovy:510)
    at NiFiDeploy.stopControllerService(NiFiDeploy.groovy:470)
    at NiFiDeploy$_handleUndeploy_closure5.doCall(NiFiDeploy.groovy:78)
    at NiFiDeploy.handleUndeploy(NiFiDeploy.groovy:74)
    at NiFiDeploy.run(NiFiDeploy.groovy:539)
```

[dbtest.zip](https://github.com/aperepel/nifi-api-deploy/files/230742/dbtest.zip)

This is nifi 6.0.

**Comment by aperepel** [comment] 2016-04-21 21:23
Thank you, I will look into these in the next couple days.

**Comment by aperepel** [comment] 2016-04-22 14:13
Hi @hijakk . I've been testing this template re-deployment, and here's what I found.

I wasn't able to reproduce this particular error, but saw some other. I was able to get rid of them all by dropping the CS uuid reference from the deployment spec file, e.g.:

```
controllerServices:
  T1:
    state: ENABLED
    config:
      Database Connection URL: jdbc:postgresql://postgres/postgres
      Database Driver Jar Url: file:///opt/postgresql-9.4.1208.jre7.jar
processGroups:
  db service:
    processors:
      ExecuteSQL:
        config:
          # note this is dropped - Database Connection Pooling Service: bd5050da-d297-4e65-b73e-8209bf855670
          SQL select query: SELECT * FROM users;
```

I am able to re-deploy now. Would be interesting to see how the behavior changes when multiple CS of the same type exist and not auto-wired, will talk to the engineering team.

**Comment by hijakk** [comment] 2016-04-22 14:36
Confirming that removing the UUID reference in the processor appears to resolve the issue on my end too

**Comment by aperepel** [comment] 2016-04-22 14:47
Great, thanks for confirming.

**Comment by aperepel** [comment] 2016-04-22 16:32
Hey @hijakk , I might be onto something here, could you please update to the latest and have a few runs (with the UUID in YAML). I'm looking to see how the T1 controller UUID is changing (it seems to be different from the one in the template).

**Comment by hijakk** [comment] 2016-04-22 18:18
Howdy - different error for me this time. With the original file (with UUID) I'm getting:

```
Caught: java.lang.AssertionError: Client ID must be provided. Expression: client. Values: client = null
java.lang.AssertionError: Client ID must be provided. Expression: client. Values: client = null
    at NiFiDeploy.run(NiFiDeploy.groovy:544)
```

Actually, getting the same error even without UUID now

**Comment by aperepel** [comment] 2016-04-22 18:56
Yeah, that's just me closing a loophole, otherwise comment messages have 'null' as a user who made the change. Just ensure you have a client id specified either in the deployment spec or on cli.

**Comment by hijakk** [comment] 2016-04-22 20:14
Ah yeah, ok. Adding '-c' option works on the command line now. Both files (with/without UUID) successfully deploy, but the one WITH shows an error on the DB connection processor, as screen shotted here.
![screen shot 2016-04-22 at 1 13 08 pm](https://cloud.githubusercontent.com/assets/2235149/14753743/1e731bf4-088c-11e6-8823-337644c8793b.png)

**Comment by aperepel** [comment] 2016-04-25 13:59
@hijakk I was able to get to the root cause of what was going on after talking to the NiFi team. Basically, NiFi will force-generate the new CS uuid upon template instantiation. The fact it works when uuid is omitted from a deployment spec is just a coincidence, it will break as soon as another CS of the same type is added.

To address this, I will be updating the code to resolve CS references by name.

**Comment by hijakk** [comment] 2016-04-25 14:16
Very interesting, thank you for the update and all the effort on this!

**Closed as completed** 2016-04-28 18:42 UTC
Labels: bug, enhancement

**Comment by aperepel** [comment] 2016-04-28 18:43
Made improvements to support CS by reference. Check out https://github.com/aperepel/nifi-api-deploy/wiki/Advanced-Deployment-Spec-Syntax as well.
